### ISSUE TITLE
Shuffle function should never return original array

### ISSUE THREAD

**Issue by chronoDave** [chronoDave/Doombox#55]
Shuffle function should reshuffle in the case that the shuffled array is equal to the original array

**Comment by sbab** [comment]
Should be fixed by #57. Happy Hacktoberfest!

**Comment by chronoDave** [comment]
Implement Knuth Shuffle

**Comment by chronoDave** [comment]
Implement performance test to compare @sbab 's shuffle versus Knuth shuffle
